[server]
headless = true
runOnSave = false
fileWatcherType = "none"
maxUploadSize = 50

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[theme]
primaryColor = "#E36414"
backgroundColor = "#F8FAFB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A1A2E"
font = "sans serif"
